miky_admin_mail:
    resource: "@MikyMailBundle/Resources/config/routing/back.yml"
    prefix : /%miky_admin.admin_path%

miky_app_mail:
    resource: "@MikyMailBundle/Resources/config/routing/front.yml"
    prefix : /mail

miky_api_mail:
    resource: "@MikyMailBundle/Resources/config/routing/api.yml"
    prefix : /api/mail
