<?php

namespace Miky\Bundle\MailBundle\Repository;

/**
 * MailTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
