<?php

namespace Miky\Bundle\MailBundle\Repository;

/**
 * PredefinedMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredefinedMailRepository extends \Doctrine\ORM\EntityRepository
{
}
