<?php

namespace Miky\Bundle\MailBundle\Repository;

/**
 * PredefinedMailTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PredefinedMailTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
