miky_resource:
    drivers:
        - doctrine/orm
    resources:
        miky.mail_type:
            classes:
                model: %mail_type.entity.class%
            contexts:
                admin: ~
miky_grid:
    grids:
        miky_admin_mail_type:
            driver:
                options:
                    class: %mail_type.entity.class%
            sorting:
                createdAt:
                    path: createdAt
                    direction: asc
            fields:
                name:
                    type: string
                    label: miky.ui.name
                enabled:
                    type: twig
                    label: miky.ui.enabled
                    options:
                        template: MikyAdminBundle:Grid/Field:enabled.html.twig
            filters:
                name:
                    type: string
                    label: miky.ui.name
                enabled:
                    type: boolean
                    label: miky.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

