miky_user_admin_security:
    resource: "@MikyUserBundle/Resources/config/routing/admin/security.yml"
    prefix : /%miky_admin.admin_path%

miky_mail_admin_predefined_mail_edit:
    path: /predefined_mail
    defaults:
        _controller: MikyMailBundle:Admin/PredefinedMailAdmin:update