adevis_admin_project:
    resource: |
        alias: adevis.project
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: adevis_admin_project
        form: adevis_admin_project
        permission: true
        vars:
            all:
                subheader: adevis.ui.manage_projects
                templates:
            index:
                icon: cube
    type: adevis.resource
