miky_admin_project:
    resource: |
        alias: miky.project
        section: admin
        context: admin
        templates: MikyAdminBundle:Crud
        redirect: update
        grid: miky_admin_project
        form: miky_admin_project
        permission: true
        vars:
            all:
                subheader: miky.ui.manage_projects
                templates:
            index:
                icon: cube
    type: miky.resource
